[package]
name = "wtest"
version = "0.2.0"
authors = ["Zsolt Krüpl <hg2ecz@ham.hu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
curl = "0.4"
plotters = "0.3"
